model_name: baseline

data_dir: /workspace2/SVHF_dataset
triplet_dir: ./triplets
batch_size: 64
num_workers: 32

lr: 0.01
epoch: 1
lr_decay_factor: 0.1
patience: 1

load_model: True
load_path: ./saved/baseline/model_6.pt

val_every: 1
save_every: 1
sample_for: 20
val_sample_dir: ./val_sample
save_dir: ./saved

multi_gpu: False
gpu_ids:
    - 0
    - 1